<h2>Task 1</h2>
<p>Write a program that allows you to enter 4 numbers
and stores them in a file called “Numbers”:</p>
• 3</br>
• 45</br>
• 83</br>
• 21</br>
<p>Have a go at ‘w’ ‘r’ ‘a’</p>

In [46]:
#Create new file and add four chosen numbers
my_file = open("Numbers.txt", "w")

my_file.write(f'{input("please enter first number")}\n')
my_file.write(f'{input("please enter second number")}\n')
my_file.write(f'{input("please enter third number")}\n')
my_file.write(f'{input("please enter fourth number")}\n')

my_file.close()

In [47]:
#Append chosen number to file
my_file = open("Numbers.txt","a")

my_file.write(f'{input("please enter number to append to file")}')

my_file.close()

In [48]:
#Read numbers and print data
with open("Numbers.txt","r") as myfile:
    data = myfile.read().replace('\n',',')
    print(data)
myfile.close()

1,2,3,4,27


<h2>Task 2</h2>
<p>Write a program to ask a student for their percentage  mark and convert this to a grade.</p>
<p>The conversion will be done in a function called mark_grade</p>

In [97]:
#List of Grades and Percentages
grade_values = {
    80:"A*",
    70:"A",
    60:"B",
    50:"C",
    40:"D",
    0:"F"
}

#Create function to run percentage_mark agains grade_values
def grade_conversion(percentage_mark):
    for percentage, grade in grade_values.items():
        if percentage_mark >= percentage:
            print(f"Grade Achieved: {grade}") 
            break

try:
    grade_conversion(float(input("Please enter your percentage mark")))
except:
    print("Please enter a numeric value")

Grade Achieved: C


<h2>Task 2 Extension</h2>
• Ask the user for their target grade and print this with their
mark</br>
• If their target grade > exam grade display a suitable
message</br>
• If their target grade = exam grade display a suitable
message</br>
• If their target grade < exam grade display a suitable
message</br>

In [130]:
try:
    desired_grade = str(input("Please enter your target grade"))
except:
    print("Please enter a string value")

try:
    student_percentage = float(input("Please enter your percentage mark"))
except:
    print("Please enter a numeric value")

def grade_conversion_with_target(percentage_mark, target_grade):
    for percentage, grade in grade_values.items():
        actual_target_diff = 0
        if percentage_mark >= percentage:
            print(f"Target Grade: {target_grade}") 
            print(f"Grade Achieved: {grade}") 
            for list_percentage, list_grade in grade_values.items():
                if target_grade == list_grade:
                    actual_target_diff = list_percentage - percentage
                    break
            if actual_target_diff == 0:
                print("Target achieved well done!!!")
            elif actual_target_diff < 0:
                print("You went above and beyond well done!!!")
            else:
                print("You didn't reach your target grade, better luck next time.")
            break


grade_conversion_with_target(student_percentage,desired_grade)

Target Grade: C
Grade Achieved: B
You went above and beyond well done!!!


<h1> Home Learning Project Numpy</h1>

In [134]:
#import necessary packages
import numpy as np

1. Create a 1D array of numbers from 0 to 9

In [171]:
array1 = np.arange(0,10)

print(array1)

[0 1 2 3 4 5 6 7 8 9]


2. Create a 3x3 NumPy array of all Boolean value Trues

In [155]:
array2 = np.ones((3,3))
print(array2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


3. Extract all odd numbers from an array of 1-10

In [173]:
array3 = np.arange(1,11)

array3_odd = array3[array3%2==1]

print(array3_odd)

[1 3 5 7 9]


4. Replace all odd numbers in an array of 1-10 with the value -1

In [180]:
array4 = np.arange(1,11)
array4_odd_replace = np.where(array4%2 == 1, -1, array4)
print(array4_odd_replace)


[-1  2 -1  4 -1  6 -1  8 -1 10]


5. Convert a 1D array to a 2D array with 2 rows

In [181]:
array5 = np.arange(1,11)
array5_2D = array5.reshape(2, 5)
print(array5_2D)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


6. Create two arrays a and b, stack these two arrays vertically use the np.dot and np.sum to calculate totals

In [201]:
a = np.arange(1,10).reshape(3,3)
b = np.arange(11,20).reshape(3,3)
c = np.dot(a,b)
d = np.sum(c)

print(a)
print(b)
print(c)
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 90  96 102]
 [216 231 246]
 [342 366 390]]
2079


<h2>Extension</h2>

1. Create the following pattern without hardcoding. Use only NumPy functions. array ([1,1,1,2,2,2,3,3,3,1,2,3,1,2,3,1,2,3])

In [324]:
a = np.ones([6,3])
a[1] = a[0]+a[0]
a[2] = a[0]+a[1]
a[3:6][:,1] = a[1]
a[3:6][:,2] = a[2]
b = np.concatenate(a)
print(b)

[1. 1. 1. 2. 2. 2. 3. 3. 3. 1. 2. 3. 1. 2. 3. 1. 2. 3.]


2. In two arrays a ( 1,2,3,4,5) and b ( 4,5,6,7,8,9) – remove all repeating items present in array b

In [310]:
a = np.arange(1,6)
b = np.arange(4,10)
data = np.setdiff1d(a, b)
print(data)

[1 2 3]


3. Get all items between 3 and 7 from a and b and sum them together

In [326]:
a = np.arange(1,6)
b = np.arange(4,10)
c = np.concatenate((a, b))
print(c)
c[np.logical_and(c>3,c<7)].sum()

[1 2 3 4 5 4 5 6 7 8 9]


24